import React from 'react';
import { AlertOctagon, AlertTriangle, BarChart3, CheckCircle2, ChevronRight, CircleAlert, CircleDollarSign, DollarSign, HelpCircle, Landmark, Percent, PlusCircle, ShieldCheck, Sparkles, TrendingDown, TrendingUp } from 'lucide-react';
import { Bar, BarChart, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { useFinance } from '../context/FinanceContext';
import { formatCurrency, formatDecimal, formatNumber, formatPercent } from '../utils/formatters';
import { TabType } from './Navbar';
import { DEMO_DATA_CONTEXT } from '../data';
import { buildOperationalPriorities, getCommercialHighlights } from '../utils/operationalPriorities';

interface CockpitDashboardProps { onNavigate: (tab: TabType) => void; onOpenSaleModal: () => void; onOpenNolaModal: () => void; onOpenCostModal: () => void; }
type Channel = 'B2C' | 'B2B';

export const CockpitDashboard: React.FC<CockpitDashboardProps> = ({ onNavigate, onOpenSaleModal, onOpenNolaModal }) => {
  const { currentDRE, pecReais, pecUnits, weightedMCPercent, totalNolaLossReais, totalNolaDiscardedUnits, productCalculations, paretoLossReasons, sectorLosses, weeklyLossTrends, sales, breakEvenStatus, lowStockSupplies, zeroStockSupplies, getStockIntelligence, getCommercialPerformance } = useFinance();
  const hasSales = currentDRE.grossRevenue > 0;
  const isPositiveResult = currentDRE.operationalProfit >= 0;
  const hasValidBreakEven = breakEvenStatus === 'valid';
  const stockIntelligence = getStockIntelligence();
  const criticalStockItems = stockIntelligence.items.filter((item) => item.risk === 'critical');
  const attentionStockItems = stockIntelligence.items.filter((item) => item.risk === 'attention');
  const principalStockRisk = criticalStockItems[0] ?? attentionStockItems[0];
  const commercialPerformance = getCommercialPerformance();

  // Mesmas premissas do FinanceContext: impostos por canal + custo variável real com perdas rateadas.
  const channelPerformance = (['B2C', 'B2B'] as Channel[]).map((channel) => {
    const records = sales.filter((sale) => sale.channel === channel);
    const revenue = records.reduce((total, sale) => total + sale.totalRevenue, 0);
    const margin = records.reduce((total, sale) => {
      const product = productCalculations[sale.productCode];
      const taxRate = sale.taxRateApplied ?? (channel === 'B2C' ? product?.product.taxRateB2C : product?.product.taxRateB2B) ?? (channel === 'B2C' ? 7.5 : 5.5);
      const costUnit = sale.financialSnapshotVersion
        ? (sale.directCostUnit ?? sale.variableCostUnit) + sale.allocatedLossUnit
        : product?.realVariableCost ?? sale.variableCostUnit + sale.allocatedLossUnit;
      const cost = costUnit * sale.quantityUnits;
      return total + sale.totalRevenue * (1 - taxRate / 100) - cost;
    }, 0);
    return { channel, label: channel, revenue, margin, marginPercent: revenue > 0 ? margin / revenue * 100 : 0, participation: currentDRE.grossRevenue > 0 ? revenue / currentDRE.grossRevenue * 100 : 0 };
  });

  const productPerformance = Object.values(productCalculations).map((calculation) => {
    const records = sales.filter((sale) => sale.productCode === calculation.product.code);
    const revenue = records.reduce((total, sale) => total + sale.totalRevenue, 0);
    const margin = records.reduce((total, sale) => {
      const rate = sale.taxRateApplied ?? (sale.channel === 'B2C' ? calculation.product.taxRateB2C : calculation.product.taxRateB2B);
      const costUnit = sale.financialSnapshotVersion
        ? (sale.directCostUnit ?? sale.variableCostUnit) + sale.allocatedLossUnit
        : calculation.realVariableCost;
      return total + sale.totalRevenue * (1 - rate / 100) - costUnit * sale.quantityUnits;
    }, 0);
    return { code: calculation.product.code, name: calculation.product.name, shortName: calculation.product.name.replace('Lasanha ', '').replace('Rondelli ', ''), revenue, margin, marginPercent: revenue > 0 ? margin / revenue * 100 : 0, totalLoss: calculation.totalLossCostNola };
  }).filter((product) => product.revenue > 0).sort((a, b) => b.marginPercent - a.marginPercent);

  const bestProduct = productPerformance[0];
  const lowestProduct = productPerformance.at(-1);
  const highestContribution = [...productPerformance].sort((a, b) => b.margin - a.margin)[0];
  const bestChannel = [...channelPerformance].sort((a, b) => b.marginPercent - a.marginPercent)[0];
  const lowestChannel = [...channelPerformance].sort((a, b) => a.marginPercent - b.marginPercent)[0];
  const topLosses = paretoLossReasons.slice(0, 5);
  const topLoss = topLosses[0];
  const topSector = sectorLosses[0];
  const criticalWeek = [...weeklyLossTrends].sort((a, b) => b.totalCost - a.totalCost)[0];
  const mostImpactedProduct = [...productPerformance].sort((a, b) => b.totalLoss - a.totalLoss)[0];
  const topThreeLossShare = topLosses.slice(0, 3).reduce((total, item) => total + item.percentage, 0);
  const financialStatus = !hasSales ? 'Não há vendas suficientes para consolidar a situação financeira.' : breakEvenStatus !== 'valid' ? 'A margem de contribuição não é positiva. O ponto de equilíbrio não é atingível nas condições atuais.' : isPositiveResult ? 'A margem de contribuição atual é suficiente para cobrir os custos fixos considerados na base demonstrativa.' : 'A margem de contribuição atual não é suficiente para cobrir os custos fixos considerados na base demonstrativa.';
  const commercialHighlights = getCommercialHighlights(commercialPerformance);
  const principalGoal = commercialHighlights.primary;
  const operationalPriorities = buildOperationalPriorities({
    commercial: commercialPerformance,
    stock: stockIntelligence,
    productMetrics: productPerformance.map((product) => ({ code: product.code, name: product.name, units: sales.filter((sale) => sale.productCode === product.code).reduce((total, sale) => total + sale.quantityUnits, 0), marginPercent: product.marginPercent })),
    operationalProfit: currentDRE.operationalProfit,
    topLoss: topLoss ? { reason: topLoss.reason, totalCost: topLoss.totalCost, percentage: topLoss.percentage } : undefined,
  });

  return <div className="cockpit-refined space-y-6">
    <div className="cockpit-signal-row grid grid-cols-1 gap-3 xl:grid-cols-2">
    <section className="cockpit-signal cockpit-signal-stock rounded-2xl border border-[#CFF2FA] bg-[#F9FEFF] p-4 text-sm text-neutral-700"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-[#087B9F]">Inteligência de estoque</p><p className="mt-1"><button onClick={() => onNavigate('inventory')} className="font-semibold text-[#08627F] hover:underline">{criticalStockItems.length} insumo(s) crítico(s)</button> · {attentionStockItems.length} em atenção · físico: {zeroStockSupplies.length} zerado(s) e {lowStockSupplies.length} baixo(s).</p>{principalStockRisk ? <p className="mt-1 text-xs text-neutral-600">Principal risco: <strong>{principalStockRisk.supply.name}</strong> · {principalStockRisk.coverageDays === undefined ? 'cobertura indisponível' : `${principalStockRisk.coverageDays.toFixed(1).replace('.', ',')} dias`} · {principalStockRisk.affectedProducts.join(', ') || 'sem produto vinculado'}. <strong>{principalStockRisk.action}</strong></p> : <p className="mt-1 text-xs text-neutral-600">Configure ficha técnica e registre vendas para calcular consumo e cobertura.</p>}</div><button onClick={() => onNavigate('inventory')} className="w-fit text-xs font-semibold text-[#08627F] hover:underline">Ver inteligência de estoque <ChevronRight className="inline h-3.5 w-3.5" /></button></div></section>
    <section className="cockpit-signal cockpit-signal-commercial rounded-2xl border border-[#CAE79A] bg-[#F4FAEA] p-4 text-sm text-neutral-700"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-[#5F9C1C]">Desempenho comercial</p>{principalGoal ? <><p className="mt-1"><strong>{principalGoal.label}</strong> · meta {formatCurrency(principalGoal.goal.revenueTarget)} · realizado {formatCurrency(principalGoal.revenueActual)}.</p><p className="mt-1 text-xs text-neutral-600">Atingimento: <strong>{principalGoal.revenueAchievement === undefined ? '— sem base de meta' : `${formatDecimal(principalGoal.revenueAchievement, 1)}%`}</strong> · desvio {formatCurrency(principalGoal.revenueDeviation)} · {principalGoal.status === 'achieved' ? 'Meta atingida' : principalGoal.status === 'in_progress' ? 'Dentro do ritmo' : principalGoal.status === 'below' ? 'Abaixo do ritmo' : principalGoal.remainingDays === undefined ? 'Período encerrado' : 'Dados insuficientes'}{principalGoal.status !== 'achieved' && principalGoal.remainingDays !== undefined && principalGoal.revenueDailyPace !== undefined ? ` · ritmo: ${formatCurrency(principalGoal.revenueDailyPace)}/dia` : ''}.</p><div className="mt-2 flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-white px-2 py-1">Canal: <strong>{commercialHighlights.bestChannel ? `${commercialHighlights.bestChannel.item.label} · ${formatDecimal(commercialHighlights.bestChannel.achievement ?? 0, 1)}%` : 'sem meta comparável'}</strong></span><span className="rounded-full bg-white px-2 py-1">Produto: <strong>{commercialHighlights.bestProduct ? `${commercialHighlights.bestProduct.item.label} · ${formatDecimal(commercialHighlights.bestProduct.achievement ?? 0, 1)}%` : 'sem meta comparável'}</strong></span></div></> : <p className="mt-1">{commercialPerformance.hasSales ? 'Há vendas registradas, mas nenhuma meta comercial cadastrada.' : 'Cadastre metas e registre vendas para acompanhar o desempenho comercial.'}</p>}</div><button onClick={() => onNavigate('sales')} className="w-fit text-xs font-semibold text-[#426D12] hover:underline">Ver metas e desempenho <ChevronRight className="inline h-3.5 w-3.5" /></button></div></section>
    </div>
    <section className="cockpit-hero relative overflow-hidden rounded-2xl border border-neutral-200 border-l-4 border-l-[#FFB800] bg-white p-5 shadow-sm">
      <div className="pointer-events-none absolute -bottom-10 -right-10 h-56 w-56 rounded-full bg-[#FFB800]/10 blur-3xl" />
      <div className="relative flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="mb-1 flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-[#D99000]"><Sparkles className="h-4 w-4" /> Central de decisão gerencial</div><h1 className="text-xl font-bold tracking-tight text-[#111111] sm:text-2xl">Cockpit Executivo</h1><p className="mt-1 max-w-3xl text-sm text-neutral-600">Situação financeira, rentabilidade, perdas e prioridades para a Guardiões da Lasanha.</p></div><div className="flex flex-wrap gap-2"><button onClick={onOpenSaleModal} className="flex items-center gap-2 rounded-xl bg-[#75B82A] px-3.5 py-2 text-xs font-semibold text-white shadow-sm hover:bg-[#8CCB35]"><PlusCircle className="h-4 w-4" />Lançar Venda</button><button onClick={onOpenNolaModal} className="flex items-center gap-2 rounded-xl bg-[#C92F0A] px-3.5 py-2 text-xs font-semibold text-white shadow-sm hover:bg-[#E33B0C]"><AlertOctagon className="h-4 w-4" />Lançar Perda</button><button onClick={() => onNavigate('guide')} className="flex items-center gap-2 rounded-xl border border-neutral-300 bg-white px-3.5 py-2 text-xs font-semibold text-neutral-700 hover:bg-[#F7F7F5]"><HelpCircle className="h-4 w-4 text-[#D99000]" />Guia Didático</button></div></div>
      <div className="cockpit-context relative mt-4 flex flex-wrap gap-x-4 gap-y-1 rounded-lg border border-neutral-200 bg-[#F7F7F5] px-3 py-2 text-[11px] text-neutral-600"><strong className="text-neutral-800">{DEMO_DATA_CONTEXT.label}</strong><span>Vendas: {DEMO_DATA_CONTEXT.sales.periodLabel}</span><span>Custos fixos: {DEMO_DATA_CONTEXT.fixedCosts.periodLabel}</span><span>Perdas: {DEMO_DATA_CONTEXT.nolaLosses.periodLabel}</span></div>
    </section>

    <section className="cockpit-executive-kpis grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
      <KpiCard label="Receita bruta" value={hasSales ? formatCurrency(currentDRE.grossRevenue) : '—'} description="No período demonstrativo" icon={CircleDollarSign} tone="neutral" />
      <KpiCard label="Margem de contribuição" value={hasSales ? formatCurrency(currentDRE.contributionMargin) : '—'} description="Após impostos e custos variáveis" icon={DollarSign} tone="highlight" />
      <KpiCard label="Resultado operacional" value={hasSales ? formatCurrency(currentDRE.operationalProfit) : '—'} description={hasSales ? `${formatPercent(currentDRE.operationalProfitPercent)} da receita bruta` : 'Aguardando vendas'} icon={isPositiveResult ? TrendingUp : TrendingDown} tone={isPositiveResult && hasSales ? 'positive' : 'critical'} />
      <KpiCard label="Ponto de equilíbrio" value={hasValidBreakEven ? formatCurrency(pecReais) : 'Não atingível'} description={hasValidBreakEven ? `${formatNumber(pecUnits)} unidades no mix atual` : 'Margem não permite PEC válido'} icon={ShieldCheck} tone={hasValidBreakEven ? 'info' : 'critical'} />
    </section>

    <ChartPanel className="cockpit-main-chart" eyebrow="Evolução" title="Receita e margem por canal" description="Leitura resumida do recorte demonstrativo atual." action="Ver vendas" onAction={() => onNavigate('sales')}><ResponsiveContainer width="100%" height="100%"><BarChart data={channelPerformance} margin={{ top: 8, right: 8, left: 0, bottom: 0 }}><XAxis dataKey="label" tick={{ fontSize: 11, fill: '#64748b' }} /><YAxis tick={{ fontSize: 11, fill: '#64748b' }} tickFormatter={(value) => `R$ ${(value / 1000).toFixed(0)}k`} /><Tooltip formatter={(value: number) => formatCurrency(value)} /><Bar dataKey="revenue" name="Receita bruta" fill="#00A6D7" radius={[5, 5, 0, 0]} /><Bar dataKey="margin" name="Margem de contribuição" fill="#9DDD25" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></ChartPanel>

    <section className={`cockpit-status rounded-2xl border p-5 shadow-sm ${!hasSales ? 'border-[#FFEDB0] bg-[#FFF8E6]' : isPositiveResult ? 'border-[#CAE79A] bg-[#F4FAEA]' : 'border-[#FFB79B] bg-[#FFF0EA]'}`}><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3">{isPositiveResult && hasSales ? <CheckCircle2 className="mt-0.5 h-6 w-6 text-[#5F9C1C]" /> : <CircleAlert className="mt-0.5 h-6 w-6 text-[#C92F0A]" />}<div><p className="text-xs font-bold uppercase tracking-wide">Saúde financeira</p><h2 className="mt-1 text-base font-bold text-[#111111]">{isPositiveResult && hasSales ? 'Operação cobre os custos fixos' : 'Atenção à cobertura de custos'}</h2><p className="mt-1 max-w-3xl text-sm leading-relaxed text-neutral-700">{financialStatus}</p></div></div><button onClick={() => onNavigate('dre')} className="flex w-fit items-center gap-1 text-xs font-semibold text-[#08627F] hover:text-[#06495E]">Ver DRE gerencial <ChevronRight className="h-3.5 w-3.5" /></button></div></section>

    <section><div className="mb-3 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-[#087B9F]">Visão financeira</p><h2 className="text-lg font-bold text-[#111111]">Indicadores que orientam o resultado</h2></div><p className="hidden text-xs text-neutral-500 sm:block">MC sobre receita bruta.</p></div><div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-12"><KpiCard className="xl:col-span-3" label="Resultado operacional" value={hasSales ? formatCurrency(currentDRE.operationalProfit) : '—'} description={hasSales ? `${formatPercent(currentDRE.operationalProfitPercent)} da receita bruta` : 'Aguardando vendas'} icon={isPositiveResult ? TrendingUp : TrendingDown} tone={isPositiveResult && hasSales ? 'positive' : 'critical'} /><KpiCard className="xl:col-span-3" label="Margem de contribuição" value={hasSales ? formatCurrency(currentDRE.contributionMargin) : '—'} description="Após impostos e custos variáveis" icon={DollarSign} tone="highlight" /><KpiCard className="xl:col-span-2" label="MC sobre receita bruta" value={hasSales ? formatPercent(weightedMCPercent) : '—'} description="Índice de contribuição" icon={Percent} tone="highlight" /><KpiCard className="xl:col-span-2" label="Ponto de equilíbrio" value={hasValidBreakEven ? formatCurrency(pecReais) : 'Não atingível'} description={hasValidBreakEven ? `${formatNumber(pecUnits)} unidades no mix atual` : 'Margem não permite PEC válido'} icon={ShieldCheck} tone={hasValidBreakEven ? 'info' : 'critical'} /><KpiCard className="xl:col-span-2" label="Receita líquida" value={hasSales ? formatCurrency(currentDRE.netRevenue) : '—'} description={`Bruta: ${formatCurrency(currentDRE.grossRevenue)}`} icon={CircleDollarSign} tone="neutral" /><KpiCard className="xl:col-span-2" label="Custos fixos" value={formatCurrency(currentDRE.fixedCostsTotal)} description="Referência mensal" icon={Landmark} tone="attention" /><KpiCard className="xl:col-span-2" label="Perdas" value={formatCurrency(totalNolaLossReais)} description={`${formatNumber(totalNolaDiscardedUnits)} unidades`} icon={AlertOctagon} tone="critical" /></div></section>

    <section className="grid grid-cols-1 gap-6 xl:grid-cols-5"><ChartPanel className="xl:col-span-3" eyebrow="Rentabilidade" title="Onde a empresa ganha mais dinheiro?" description="Receita e margem de contribuição por canal, no recorte atual." action="Ver vendas" onAction={() => onNavigate('sales')}><ResponsiveContainer width="100%" height="100%"><BarChart data={channelPerformance} margin={{ top: 8, right: 8, left: 0, bottom: 0 }}><XAxis dataKey="label" tick={{ fontSize: 11, fill: '#64748b' }} /><YAxis tick={{ fontSize: 11, fill: '#64748b' }} tickFormatter={(value) => `R$ ${(value / 1000).toFixed(0)}k`} /><Tooltip formatter={(value: number) => formatCurrency(value)} /><Bar dataKey="revenue" name="Receita bruta" fill="#00A6D7" radius={[5, 5, 0, 0]} /><Bar dataKey="margin" name="Margem de contribuição" fill="#9DDD25" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></ChartPanel><aside className="rounded-2xl border border-neutral-200/80 bg-white p-6 shadow-xs xl:col-span-2"><p className="text-xs font-bold uppercase tracking-wider text-[#D99000]">Rentabilidade</p><h2 className="text-lg font-bold text-[#111111]">Resumo por produto</h2><div className="mt-4 space-y-3"><MetricRow label="Maior margem" value={bestProduct ? `${bestProduct.name} · ${formatPercent(bestProduct.marginPercent)}` : 'Sem vendas'} tone="positive" /><MetricRow label="Menor margem" value={lowestProduct ? `${lowestProduct.name} · ${formatPercent(lowestProduct.marginPercent)}` : 'Sem vendas'} tone="attention" /><MetricRow label="Maior contribuição" value={highestContribution ? `${highestContribution.name} · ${formatCurrency(highestContribution.margin)}` : 'Sem vendas'} tone="info" /><MetricRow label="Melhor canal" value={bestChannel ? `${bestChannel.label} · ${formatPercent(bestChannel.marginPercent)}` : 'Sem vendas'} tone="info" /></div>{bestChannel && lowestChannel && bestChannel.channel !== lowestChannel.channel && <p className="mt-4 rounded-xl bg-[#EAF9FD] p-3 text-xs leading-relaxed text-[#06495E]">{bestChannel.label} tem MC {Math.abs(bestChannel.marginPercent - lowestChannel.marginPercent).toFixed(1).replace('.', ',')} p.p. superior a {lowestChannel.label}.</p>}</aside></section>

    <ChartPanel eyebrow="Rentabilidade por produto" title="Margem de contribuição sobre receita bruta" description="Produtos com vendas no recorte demonstrativo atual." action="Ver custos e precificação" onAction={() => onNavigate('pricing')}><ResponsiveContainer width="100%" height="100%"><BarChart data={productPerformance} layout="vertical" margin={{ top: 4, right: 28, left: 35, bottom: 4 }}><XAxis type="number" unit="%" tick={{ fontSize: 11, fill: '#64748b' }} /><YAxis type="category" dataKey="shortName" width={100} tick={{ fontSize: 11, fill: '#475569' }} /><Tooltip formatter={(value: number) => formatPercent(value)} /><Bar dataKey="marginPercent" name="MC sobre receita bruta" radius={[0, 5, 5, 0]}>{productPerformance.map((product, index) => <Cell key={product.code} fill={index === productPerformance.length - 1 ? '#F66A3A' : '#75B82A'} />)}</Bar></BarChart></ResponsiveContainer></ChartPanel>

    <section className="grid grid-cols-1 gap-6 xl:grid-cols-5"><ChartPanel className="xl:col-span-3" eyebrow="Perdas" title="Onde a empresa está perdendo dinheiro?" description="Pareto de causas por impacto financeiro — acumulado de 27 semanas." action="Ver perdas" onAction={() => onNavigate('nola')}><ResponsiveContainer width="100%" height="100%"><BarChart data={topLosses} layout="vertical" margin={{ top: 4, right: 20, left: 80, bottom: 4 }}><XAxis type="number" tick={{ fontSize: 11, fill: '#64748b' }} tickFormatter={(value) => `R$ ${(value / 1000).toFixed(1)}k`} /><YAxis type="category" dataKey="reason" width={120} tick={{ fontSize: 10, fill: '#475569' }} /><Tooltip formatter={(value: number) => formatCurrency(value)} /><Bar dataKey="totalCost" name="Perda financeira" fill="#FFBC0D" radius={[0, 5, 5, 0]} /></BarChart></ResponsiveContainer></ChartPanel><aside className="rounded-2xl border border-neutral-200/80 bg-white p-6 shadow-xs xl:col-span-2"><p className="text-xs font-bold uppercase tracking-wider text-[#C92F0A]">Impacto das perdas</p><h2 className="text-lg font-bold text-[#111111]">Resumo operacional</h2><div className="mt-4 space-y-3"><MetricRow label="Principal causa" value={topLoss ? `${topLoss.reason} · ${formatCurrency(topLoss.totalCost)}` : 'Sem dados'} tone="critical" /><MetricRow label="Setor mais impactado" value={topSector ? `${topSector.sector} · ${formatCurrency(topSector.totalCost)}` : 'Sem dados'} tone="attention" /><MetricRow label="Produto mais impactado" value={mostImpactedProduct ? `${mostImpactedProduct.name} · ${formatCurrency(mostImpactedProduct.totalLoss)}` : 'Sem dados'} tone="critical" /><MetricRow label="Semana crítica" value={criticalWeek ? `${criticalWeek.week} · ${formatCurrency(criticalWeek.totalCost)}` : 'Sem dados'} tone="attention" /></div>{topLoss && <p className="mt-4 rounded-xl bg-[#FFF0EA] p-3 text-xs leading-relaxed text-[#962006]">As três principais causas concentram {formatPercent(topThreeLossShare)} do valor perdido.</p>}</aside></section>

    <section className="cockpit-priorities rounded-2xl border border-neutral-200/80 bg-white p-6 shadow-xs"><p className="text-xs font-bold uppercase tracking-wider text-[#D99000]">Resultado → risco → ação</p><h2 className="text-lg font-bold text-[#111111]">Prioridades operacionais</h2><p className="mt-1 text-xs text-neutral-500">Leitura derivada de metas, vendas, estoque, perdas e resultado. Recomendações não executam movimentações.</p><div className="mt-4 grid grid-cols-1 gap-3 lg:grid-cols-2">{operationalPriorities.map((priority) => <OperationalPriorityCard key={`${priority.title}-${priority.cause}`} {...priority} />)}</div></section>
  </div>;
};

function KpiCard({ label, value, description, icon: Icon, tone, className = '' }: { label: string; value: string; description: string; icon: React.ElementType; tone: 'positive' | 'critical' | 'highlight' | 'info' | 'neutral' | 'attention'; className?: string }) { const tones = { positive: 'border-[#CAE79A] bg-[#F4FAEA] text-[#314E0D]', critical: 'border-[#FFB79B] bg-[#FFF0EA] text-[#691603]', highlight: 'border-[#FFE080] bg-[#FFF8E6] text-[#5E3B00]', info: 'border-[#A7E5F2] bg-[#EAF9FD] text-[#06495E]', neutral: 'border-neutral-200 bg-white text-[#111111]', attention: 'border-[#FFEDB0] bg-[#FFF8E6] text-[#875700]' }; return <div className={`cockpit-kpi rounded-2xl border p-4 shadow-xs ${tones[tone]} ${className}`}><div className="flex items-center justify-between"><span className="text-[10px] font-bold uppercase tracking-wide opacity-80">{label}</span><Icon className="h-5 w-5" /></div><p className="mt-4 text-xl font-black tracking-tight">{value}</p><p className="mt-1 text-[11px] opacity-80">{description}</p></div>; }
function ChartPanel({ eyebrow, title, description, action, onAction, children, className = '' }: { eyebrow: string; title: string; description: string; action: string; onAction: () => void; children: React.ReactNode; className?: string }) { return <div className={`cockpit-panel rounded-2xl border border-neutral-200/80 bg-white p-6 shadow-xs ${className}`}><div className="mb-4 flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-[#087B9F]">{eyebrow}</p><h2 className="text-lg font-bold text-[#111111]">{title}</h2><p className="mt-1 text-xs text-neutral-500">{description}</p></div><button onClick={onAction} className="flex shrink-0 items-center gap-1 text-xs font-semibold text-[#08627F] hover:text-[#06495E]">{action}<ChevronRight className="h-3.5 w-3.5" /></button></div><div className="h-64">{children}</div></div>; }
function MetricRow({ label, value, tone }: { label: string; value: string; tone: 'positive' | 'critical' | 'attention' | 'info' }) { const tones = { positive: 'border-[#CAE79A] bg-[#F4FAEA] text-[#426D12]', critical: 'border-[#FFB79B] bg-[#FFF0EA] text-[#962006]', attention: 'border-[#FFEDB0] bg-[#FFF8E6] text-[#875700]', info: 'border-[#A7E5F2] bg-[#EAF9FD] text-[#06495E]' }; return <div className={`cockpit-metric-row rounded-xl border p-3 ${tones[tone]}`}><p className="text-[10px] font-bold uppercase tracking-wide opacity-80">{label}</p><p className="mt-1 text-xs font-semibold leading-relaxed text-[#111111]">{value}</p></div>; }
const PriorityCard: React.FC<{ index: number; title: string; description: string; tone: 'critical' | 'attention' | 'info' }> = ({ index, title, description, tone }) => { const tones = { critical: 'border-[#FFB79B] bg-[#FFF0EA] text-[#962006]', attention: 'border-[#FFEDB0] bg-[#FFF8E6] text-[#875700]', info: 'border-[#A7E5F2] bg-[#EAF9FD] text-[#06495E]' }; return <article className={`rounded-xl border p-4 ${tones[tone]}`}><span className="grid h-6 w-6 place-items-center rounded-full bg-white/70 text-xs font-black">{index}</span><h3 className="mt-3 text-sm font-bold text-[#111111]">{title}</h3><p className="mt-1 text-xs leading-relaxed text-neutral-700">{description}</p></article>; };
const OperationalPriorityCard: React.FC<{ title: string; cause: string; impact: string; action: string; tone: 'critical' | 'attention' | 'info' }> = ({ title, cause, impact, action, tone }) => { const tones = { critical: 'border-[#FFB79B] bg-[#FFF0EA] text-[#962006]', attention: 'border-[#FFEDB0] bg-[#FFF8E6] text-[#875700]', info: 'border-[#A7E5F2] bg-[#EAF9FD] text-[#06495E]' }; return <article className={`cockpit-priority-card rounded-xl border p-4 ${tones[tone]}`}><h3 className="text-sm font-bold text-[#111111]">{title}</h3><dl className="mt-3 space-y-2 text-xs leading-relaxed text-neutral-700"><div><dt className="font-bold text-neutral-900">Causa</dt><dd>{cause}</dd></div><div><dt className="font-bold text-neutral-900">Impacto</dt><dd>{impact}</dd></div><div><dt className="font-bold text-neutral-900">Ação recomendada</dt><dd>{action}</dd></div></dl></article>; };
