import React, { useMemo, useState } from 'react';
import { CheckCircle2, Pencil, PlusCircle, Target, Trash2, TriangleAlert } from 'lucide-react';
import { useAccess } from '../context/AccessContext';
import { useFinance } from '../context/FinanceContext';
import { CommercialGoal, ProductCode, SalesChannel } from '../types/finance';
import { CommercialGoalStatus } from '../utils/commercialGoals';
import { formatCurrency, formatDecimal, formatNumber } from '../utils/formatters';

type Draft = Omit<CommercialGoal, 'id' | 'createdAt' | 'updatedAt'>;
const blankDraft = (): Draft => ({ startDate: '', endDate: '', channel: undefined, productCode: undefined, revenueTarget: 0, unitTarget: 0 });
const statusCopy: Record<CommercialGoalStatus, { label: string; style: string }> = {
  achieved: { label: '🟢 Meta atingida', style: 'bg-[#E3F3C4] text-[#426D12]' },
  in_progress: { label: '🟡 Em andamento', style: 'bg-[#FFF8E6] text-[#875700]' },
  below: { label: '🔴 Abaixo da meta', style: 'bg-[#FFF0EA] text-[#8E240C]' },
  closed: { label: '🔴 Período encerrado', style: 'bg-[#FFF0EA] text-[#8E240C]' },
  no_target: { label: '⚪ Sem base de meta', style: 'bg-neutral-100 text-neutral-600' },
};
const metric = (target: number, actual: number, percent?: number, currency = false) => <div><strong>{currency ? formatCurrency(target) : `${formatNumber(target)} un.`}</strong><span className="block text-neutral-500">Realizado: {currency ? formatCurrency(actual) : `${formatNumber(actual)} un.`} · {percent === undefined ? '—' : `${formatDecimal(percent, 1)}%`}</span></div>;

export const CommercialPerformanceSection: React.FC = () => {
  const { products, commercialGoals, getCommercialPerformance, saveCommercialGoal, deleteCommercialGoal } = useFinance();
  const { can } = useAccess();
  const [filters, setFilters] = useState<{ from: string; to: string; channel: 'ALL' | SalesChannel; productCode: 'ALL' | ProductCode }>({ from: '', to: '', channel: 'ALL', productCode: 'ALL' });
  const [draft, setDraft] = useState<Draft>(blankDraft);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [notice, setNotice] = useState('');
  const [pendingDelete, setPendingDelete] = useState<string | null>(null);
  const report = useMemo(() => getCommercialPerformance({ from: filters.from || undefined, to: filters.to || undefined, channel: filters.channel === 'ALL' ? undefined : filters.channel, productCode: filters.productCode === 'ALL' ? undefined : filters.productCode }), [getCommercialPerformance, commercialGoals, filters]);
  const canManage = can('commercialGoals.manage');
  const save = (event: React.FormEvent) => {
    event.preventDefault();
    const result = saveCommercialGoal({ ...draft, id: editingId ?? undefined });
    setNotice(result.ok ? `Meta ${editingId ? 'atualizada' : 'cadastrada'} com sucesso.` : result.message ?? 'Não foi possível salvar a meta.');
    if (result.ok) { setDraft(blankDraft()); setEditingId(null); }
  };
  const edit = (goal: CommercialGoal) => { const { id, createdAt, updatedAt, ...next } = goal; setDraft(next); setEditingId(id); setNotice('Editando meta selecionada.'); };
  const confirmDelete = () => { if (!pendingDelete) return; const ok = deleteCommercialGoal(pendingDelete); setNotice(ok ? 'Meta excluída.' : 'Não foi possível excluir a meta.'); setPendingDelete(null); };

  return <section className="space-y-4 rounded-2xl border border-[#CFF2FA] bg-[#F9FEFF] p-5 shadow-xs sm:p-6">
    <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[#087B9F]"><Target className="h-4 w-4" /> Metas e desempenho comercial</p><h2 className="mt-1 text-lg font-bold text-[#111111]">Meta × realizado</h2><p className="mt-1 text-sm text-neutral-600">Indicador gerencial baseado somente nas vendas registradas; não altera receita, custos ou snapshots.</p></div>{canManage && <span className="w-fit rounded-full bg-[#E3F3C4] px-3 py-1 text-xs font-bold text-[#426D12]">Configuração liberada</span>}</div>

    <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><label className="field-label">Início<input aria-label="Metas período inicial" type="date" value={filters.from} onChange={(e) => setFilters((prev) => ({ ...prev, from: e.target.value }))} /></label><label className="field-label">Fim<input aria-label="Metas período final" type="date" value={filters.to} onChange={(e) => setFilters((prev) => ({ ...prev, to: e.target.value }))} /></label><label className="field-label">Canal<select aria-label="Metas filtrar canal" value={filters.channel} onChange={(e) => setFilters((prev) => ({ ...prev, channel: e.target.value as 'ALL' | SalesChannel }))}><option value="ALL">Todos</option><option value="B2C">B2C</option><option value="B2B">B2B</option></select></label><label className="field-label">Produto<select aria-label="Metas filtrar produto" value={filters.productCode} onChange={(e) => setFilters((prev) => ({ ...prev, productCode: e.target.value as 'ALL' | ProductCode }))}><option value="ALL">Todos</option>{products.map((product) => <option key={product.code} value={product.code}>{product.name}</option>)}</select></label></div>

    {canManage && <form onSubmit={save} className="rounded-xl border border-neutral-200 bg-white p-4"><div className="mb-3 flex items-center gap-2"><PlusCircle className="h-4 w-4 text-[#5F9C1C]" /><h3 className="text-sm font-bold">{editingId ? 'Editar meta' : 'Nova meta'}</h3></div><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-3"><label className="field-label">Início<input aria-label="Meta início" required type="date" value={draft.startDate} onChange={(e) => setDraft((prev) => ({ ...prev, startDate: e.target.value }))} /></label><label className="field-label">Fim<input aria-label="Meta fim" required type="date" value={draft.endDate} onChange={(e) => setDraft((prev) => ({ ...prev, endDate: e.target.value }))} /></label><label className="field-label">Canal<select aria-label="Meta canal" value={draft.channel ?? 'ALL'} onChange={(e) => setDraft((prev) => ({ ...prev, channel: e.target.value === 'ALL' ? undefined : e.target.value as SalesChannel }))}><option value="ALL">Geral</option><option value="B2C">B2C</option><option value="B2B">B2B</option></select></label><label className="field-label">Produto<select aria-label="Meta produto" value={draft.productCode ?? 'ALL'} onChange={(e) => setDraft((prev) => ({ ...prev, productCode: e.target.value === 'ALL' ? undefined : e.target.value as ProductCode }))}><option value="ALL">Todos os produtos</option>{products.map((product) => <option key={product.code} value={product.code}>{product.name}</option>)}</select></label><label className="field-label">Meta faturamento<input aria-label="Meta faturamento" type="number" min="0" step="0.01" value={draft.revenueTarget} onChange={(e) => setDraft((prev) => ({ ...prev, revenueTarget: Number(e.target.value) }))} /></label><label className="field-label">Meta quantidade<input aria-label="Meta quantidade" type="number" min="0" step="1" value={draft.unitTarget} onChange={(e) => setDraft((prev) => ({ ...prev, unitTarget: Number(e.target.value) }))} /></label></div><div className="mt-3 flex flex-wrap gap-2"><button className="rounded-lg bg-[#75B82A] px-3 py-2 text-xs font-bold text-white hover:bg-[#5F9C1C]" type="submit">{editingId ? 'Salvar alterações' : 'Cadastrar meta'}</button>{editingId && <button type="button" onClick={() => { setEditingId(null); setDraft(blankDraft()); }} className="rounded-lg border border-neutral-300 px-3 py-2 text-xs font-bold text-neutral-700">Cancelar edição</button>}</div></form>}
    {notice && <p role="status" className="rounded-lg border border-[#CFF2FA] bg-white px-3 py-2 text-sm text-[#06495E]">{notice}</p>}
    {pendingDelete && <div role="alertdialog" className="flex flex-wrap items-center gap-2 rounded-xl border border-[#FFB79B] bg-[#FFF0EA] p-3 text-sm text-[#691603]"><TriangleAlert className="h-4 w-4" /> Excluir esta meta? <button onClick={confirmDelete} className="rounded-md bg-[#C92F0A] px-2 py-1 text-xs font-bold text-white">Confirmar exclusão</button><button onClick={() => setPendingDelete(null)} className="rounded-md border border-[#C92F0A] px-2 py-1 text-xs font-bold">Cancelar</button></div>}

    {!report.hasGoals && <p className="rounded-xl border border-dashed border-neutral-300 bg-white px-4 py-5 text-center text-sm text-neutral-600">{report.hasSales ? 'Há dados de vendas, mas nenhuma meta cadastrada para este recorte.' : 'Não há vendas ou metas para o período selecionado.'}</p>}
    {report.alerts.length > 0 && <div className="rounded-xl border border-[#FFE080] bg-[#FFF8E6] p-3 text-sm text-[#691603]"><strong>Alertas de desempenho</strong>{report.alerts.map((item) => <p key={item.goal.id} className="mt-1">{item.alert}</p>)}</div>}
    {report.hasGoals && <div className="overflow-x-auto"><table className="min-w-[1050px] w-full text-xs"><thead className="bg-white text-left text-neutral-600"><tr><th className="p-3">Recorte</th><th>Meta</th><th>Realizado</th><th>Desvio</th><th>Atingimento</th><th>Ritmo necessário</th><th>Status</th>{canManage && <th>Ações</th>}</tr></thead><tbody className="divide-y divide-[#CFF2FA]">{report.items.map((item) => <tr key={item.goal.id}><td className="p-3 font-semibold">{item.label}<span className="mt-1 block font-normal text-neutral-500">{item.goal.startDate} até {item.goal.endDate}</span></td><td>{metric(item.goal.revenueTarget, item.revenueActual, item.revenueAchievement, true)}<div className="mt-1">{metric(item.goal.unitTarget, item.unitsActual, item.unitsAchievement)}</div></td><td>{formatCurrency(item.revenueActual)}<span className="block text-neutral-500">{formatNumber(item.unitsActual)} un.</span></td><td className={item.revenueDeviation < 0 || item.unitsDeviation < 0 ? 'text-[#C92F0A]' : 'text-[#426D12]'}>{formatCurrency(item.revenueDeviation)}<span className="block">{formatNumber(item.unitsDeviation)} un.</span></td><td>{item.revenueAchievement === undefined ? '—' : `${formatDecimal(item.revenueAchievement, 1)}%`}<span className="block text-neutral-500">{item.unitsAchievement === undefined ? '—' : `${formatDecimal(item.unitsAchievement, 1)}%`}</span></td><td>{item.status === 'achieved' ? 'Meta atingida' : item.remainingDays === undefined ? 'Período encerrado' : <>{item.revenueDailyPace === undefined ? '—' : `${formatCurrency(item.revenueDailyPace)}/dia`}<span className="block text-neutral-500">{item.unitsDailyPace === undefined ? '—' : `${formatDecimal(item.unitsDailyPace)} un./dia`} · {item.remainingDays} dia(s)</span></>}</td><td><span className={`inline-flex rounded-full px-2 py-1 font-bold ${statusCopy[item.status].style}`}>{statusCopy[item.status].label}</span></td>{canManage && <td className="whitespace-nowrap"><button aria-label={`Editar meta ${item.label}`} onClick={() => edit(item.goal)} className="rounded p-1 text-[#08627F] hover:bg-[#EAF9FD]"><Pencil className="h-4 w-4" /></button><button aria-label={`Excluir meta ${item.label}`} onClick={() => setPendingDelete(item.goal.id)} className="rounded p-1 text-[#C92F0A] hover:bg-[#FFF0EA]"><Trash2 className="h-4 w-4" /></button></td>}</tr>)}</tbody></table></div>}
  </section>;
};
